# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77a89f3a02cf5606e64eccd1156bc281"
extension_directories = [ "extensions/**" ]
web_directories = [ "." ]
name = "mudasser-subscription-app"
application_url = "https://3562-2407-d000-704-d051-c5b6-5c41-b2e5-d278.ngrok-free.app"
embedded = true
handle = "mudasser-subscription-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://3562-2407-d000-704-d051-c5b6-5c41-b2e5-d278.ngrok-free.app/webhook/app-uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_app_proxy,write_app_proxy,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_audit_events,read_customer_events,read_cart_transforms,write_cart_transforms,read_all_cart_transforms,read_validations,write_validations,read_cash_tracking,write_cash_tracking,read_channels,write_channels,read_checkout_branding_settings,write_checkout_branding_settings,write_checkouts,read_checkouts,read_customers,write_customers,write_customer_payment_methods,read_customer_payment_methods,read_delivery_customizations,write_delivery_customizations,write_inventory,read_inventory,read_legal_policies,write_legal_policies,read_locales,write_locales,write_locations,read_locations,write_marketing_events,read_marketing_events,read_markets,write_markets,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders,write_orders,read_payment_terms,write_payment_terms,read_payment_customizations,write_payment_customizations,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_purchase_options,write_purchase_options,write_reports,read_shipping,write_shipping,read_content,write_content,write_own_subscription_contracts,read_own_subscription_contracts,customer_read_metaobjects,customer_read_orders,customer_write_orders,customer_write_own_subscription_contracts,customer_read_own_subscription_contracts,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_customers,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_selling_plans,unauthenticated_read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://3562-2407-d000-704-d051-c5b6-5c41-b2e5-d278.ngrok-free.app/authenticate",
  "https://3562-2407-d000-704-d051-c5b6-5c41-b2e5-d278.ngrok-free.app/authenticate/token"
]
